import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
//Importing SessionProviderWrapper in order to have OAUTH run on the entire app without server component throwing errors for attempting to use
// import SessionProviderWrapper from "./components/SessionProviderWrapper"; No longer using nextAuth, using iron-session

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "YooView",
  description: "YouTube Homepage lookalike - Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          {children}
        </div>
      </body>
    </html>
  );
}

// Create scoped layout for searching new videos. Will create a new page
export function SearchLayout({ children }: { children: React.ReactNode }) {
  return <section>{children}</section>;
}
