//placeholder video thumbnails from Lorem Picsum will be used, as well as map function to spread array of placeholders onto component
export const placeholderVideos = [
  {
    id: "placeholder-1",
    title: "You'll never BELIEVE whats on this mans computer...",
    thumbnail: "https://picsum.photos/id/1/200/300",
    views: "1,465,832 Views",
    category: "Test",
  },
  {
    id: "placeholder-2",
    title: "You'll never BELIEVE whats on the same mans phone...",
    thumbnail: "https://picsum.photos/id/3/200/300",
    views: "14,465,832 Views",
    category: "Test",
  },
  {
    id: "placeholder-3",
    title: "Top 20 reasons why these mountains need to be EXCAVATED",
    thumbnail: "https://picsum.photos/id/29/200/300",
    views: "12,465,832 Views",
    category: "Test",
  },
  {
    id: "placeholder-4",
    title: "This city.... Theres something WRONG with it...",
    thumbnail: "https://picsum.photos/id/43/200/300",
    views: "111,465,832 Views",
    category: "Test",
  },
  {
    id: "placeholder-5",
    title: "This flower... is the most DANGEROUS flower on the planet",
    thumbnail: "https://picsum.photos/id/55/200/300",
    views: "30,465,832 Views",
    category: "Test",
  },
  {
    id: "placeholder-6",
    title: "WHO IS THIS WOMAN?????",
    thumbnail: "https://picsum.photos/id/64/200/300",
    views: "100,465,832 Views",
    category: "Test",
  },
  {
    id: "placeholder-7",
    title: "This bridge has a DARK history...",
    thumbnail: "https://picsum.photos/id/84/200/300",
    views: "23,465,832 Views",
    category: "Test",
  },
  {
    id: "placeholder-8",
    title: "Top 10 reasons why the government HATES you...",
    thumbnail: "https://picsum.photos/id/122/200/300",
    views: "6,465,832 Views",
    category: "Test",
  },
  {
    id: "placeholder-9",
    title: "There's something WORSE than a lovecraftian monster in there...",
    thumbnail: "https://picsum.photos/id/124/200/300",
    views: "65,465,832 Views",
    category: "Test",
  },
  {
    id: "placeholder-10",
    title: "This castle was built with CURSED bricks...",
    thumbnail: "https://picsum.photos/id/142/200/300",
    views: "80,465,832 Views",
    category: "Test",
  },
  {
    id: "placeholder-11",
    title: "This lightshow KILLED MILLIONS...",
    thumbnail: "https://picsum.photos/id/158/200/300",
    views: "90,465,832 Views",
    category: "Test",
  },
  {
    id: "placeholder-12",
    title: "This guitar... once belonged to a madman...",
    thumbnail: "https://picsum.photos/id/145/200/300",
    views: "465,832 Views",
    category: "Test",
  },
];
